titan: Fix up broken earpiece after soft reboot
* By mimicing 'voice-speaker' path we are
fixing issue where after soft reboot eg: change DPI
it would not work because of buffer overflow:
  tapan_slimbus_irq: overflow error on RX port 1, value 1
  Error: Start voice called in state 1

Change-Id: I7ef36e00838fdda7828e09160f71bb1884a94319